version: "2"

run:
  go: "1.22"

linters:
  default: none
  enable:
    - govet
    - revive
    - staticcheck
    - errcheck
    - ineffassign
    - unused

  settings:
    revive:
      rules:
        - name: var-naming
        - name: indent-error-flow