apiVersion: v1
kind: Secret
metadata:
  name: gophprofile-server-secret
  namespace: gophprofile
type: Opaque
stringData:
  server.yaml: |
    app:
      host: "0.0.0.0"
      port: "8080"

    postgres:
      dsn: "host=postgres port=5432 user=postgres password=postgres dbname=gophprofile sslmode=disable"

    s3:
      endpoint: "minio:9000"
      access_key: "minioadmin"
      secret_key: "minioadmin"
      bucket: "avatars"
      use_ssl: false
      region: "us-east-1"

    rabbitmq:
      url: "amqp://guest:guest@rabbitmq:5672/"
      exchange: "avatars"
      exchange_type: "direct"
      upload_routing_key: "avatar.upload"
      delete_routing_key: "avatar.delete"

    jaeger:
      name: "otel-collector"
      port: 4317

    rate_limit:
      request_per_minute: 60